// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlom3g8rocfeSmFzE0IR8tWMz-DAqS3hc',
    appId: '1:46318592762:web:7aa3c06b51a86218fc9f43',
    messagingSenderId: '46318592762',
    projectId: 'zenjshop-803ca',
    authDomain: 'zenjshop-803ca.firebaseapp.com',
    storageBucket: 'zenjshop-803ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARew00XOGQ8--njKEQApbycId72jiA1kE',
    appId: '1:46318592762:android:242856e1c2fab705fc9f43',
    messagingSenderId: '46318592762',
    projectId: 'zenjshop-803ca',
    storageBucket: 'zenjshop-803ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAws8jt9Si4vTG9i4tbhcFL0Ihem6bRQsE',
    appId: '1:46318592762:ios:9f5b8630909df297fc9f43',
    messagingSenderId: '46318592762',
    projectId: 'zenjshop-803ca',
    storageBucket: 'zenjshop-803ca.firebasestorage.app',
    iosBundleId: 'com.example.zenjshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAws8jt9Si4vTG9i4tbhcFL0Ihem6bRQsE',
    appId: '1:46318592762:ios:9f5b8630909df297fc9f43',
    messagingSenderId: '46318592762',
    projectId: 'zenjshop-803ca',
    storageBucket: 'zenjshop-803ca.firebasestorage.app',
    iosBundleId: 'com.example.zenjshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlom3g8rocfeSmFzE0IR8tWMz-DAqS3hc',
    appId: '1:46318592762:web:d74d9c4140b540c0fc9f43',
    messagingSenderId: '46318592762',
    projectId: 'zenjshop-803ca',
    authDomain: 'zenjshop-803ca.firebaseapp.com',
    storageBucket: 'zenjshop-803ca.firebasestorage.app',
  );
}
